### ISSUE TITLE
ModuleNotFoundError: No module named 'Source'

### ISSUE THREAD

**Issue by FPGA-KING** [SamanKhamesian/Human-Activity-Recognition-Time-Series-Classification#3]
ModuleNotFoundError: No module named 'Source'

I can't find google search about "Source" library.

what should I do?

Thanks.

**Comment by SamanKhamesian** [comment]
Hi,

Please pay attention that the "Source" module is our own defined module and it is a folder's name in this project. Your issue came from your current project path.

Good Luck.
